// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoListAPI.Models;

namespace TodoListAPI.Migrations
{
    [DbContext(typeof(TodoItemContext))]
    [Migration("20201015101839_userImages_tenth")]
    partial class userImages_tenth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TodoListAPI.Models.TodoItem", b =>
                {
                    b.Property<long>("todoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IsComplete")
                        .HasColumnType("int");

                    b.Property<string>("todoColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("todoCreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("todoDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("todoDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("todoImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("todoPriority")
                        .HasColumnType("int");

                    b.Property<int>("todoStatus")
                        .HasColumnType("int");

                    b.Property<string>("todoTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("todoUserId")
                        .HasColumnType("bigint");

                    b.HasKey("todoId");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("TodoListAPI.Models.User", b =>
                {
                    b.Property<long>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("userBlockStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("userCreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("userEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userImages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("userMobile")
                        .HasColumnType("bigint");

                    b.Property<string>("userPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userStatus")
                        .HasColumnType("int");

                    b.Property<string>("userUserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
